[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.22"
optimizer = true
optimizer_runs = 200
via_ir = false
ffi = false
fs_permissions = [{ access = "read", path = "./" }]

# Remappings
remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]

# Test configuration
[profile.default.fuzz]
runs = 256
max_test_rejects = 65536

# Gas report configuration
gas_reports = ["CheckIn"]
gas_reports_ignore = []

# Formatting configuration
[fmt]
bracket_spacing = true
int_types = "long"
line_length = 100
multiline_func_header = "attributes_first"
number_underscore = "thousands"
quote_style = "double"
single_line_statement_blocks = "preserve"
tab_width = 4
wrap_comments = true
